language: node_js
before_script:
    - sh -e /etc/init.d/xvfb start
    - git submodule update --init
    - cd addon-sdk
    - . bin/activate
    - cd ../
    - /usr/local/bin/firefox -v
env:
    - DISPLAY=':99.0'
script: cfx test     
